bind-key S choose-window 'join-pane -v -s "%%"'
bind-key V choose-window 'join-pane -h -s "%%"'
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key C-Right resize-pane -R
bind-key D attach-session -c '#{pane_current_path}'
bind-key -T copy-mode-vi 'y' send -X copy-selection

set-option -g detach-on-destroy off
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
# Tell tmux to pass through cursor blinking and shapes to Ghostty
set -as terminal-overrides ',xterm*:Ss=\E[%p1%d q:Se=\E[2 q'
set-option -g focus-events on
set -g mouse on
set-window-option -g mode-keys vi
set -g status-style bg=default


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
